synthetic-package: false
arb-dir: assets/i18n/
output-dir: lib/generated/i18n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated_messages.json
