import 'package:open_local_ui/core/asset.dart';

class _Asset {
  final String path;
  final AssetSource source;
  final AssetType type;

  const _Asset(this.path, this.source, this.type);
}

class Assets {
  static const all = [
    _Asset(
      'assets/graphics/animations/gpu.riv',
      AssetSource.local,
      AssetType.rivefile,
    ),
    _Asset(
      'assets/graphics/animations/human.riv',
      AssetSource.local,
      AssetType.rivefile,
    ),
    _Asset(
      'assets/metadata/ollama_models.json',
      AssetSource.local,
      AssetType.json,
    ),
    _Asset(
      'assets/graphics/logos/apache.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/arduino.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/bash.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/c.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/clojure.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/cmake.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/cpp.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/crystal.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/cs.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/css.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/dart.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/delphi.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/dockerfile.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/elixir.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/erlang.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/flutter.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/fortran.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/glsl.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/go.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/gradle.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/haskell.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/java.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/javascript.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/json.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/julia.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/kotlin.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/langchain.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/less.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/llvm.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/lua.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/makefile.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/nginx.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/nsis.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/ocaml.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/ollama.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/perl.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/php.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/powershell.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/python.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/ruby.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/rust.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/scala.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/scss.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/supabase.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/swift.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/toml.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/typescript.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/vala.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/xml.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/html.svg',
      AssetSource.local,
      AssetType.binary,
    ),
    _Asset(
      'assets/graphics/logos/yaml.svg',
      AssetSource.local,
      AssetType.binary,
    ),
  ];
}
