// Map for programming language logos
Map<String, String> programmingLanguagesLogos = {
  'apache': 'assets/graphics/logos/apache.svg',
  'arduino': 'assets/graphics/logos/arduino.svg',
  'bash': 'assets/graphics/logos/bash.svg',
  'c': 'assets/graphics/logos/c.svg',
  'clojure': 'assets/graphics/logos/clojure.svg',
  'cmake': 'assets/graphics/logos/cmake.svg',
  'cpp': 'assets/graphics/logos/cpp.svg',
  'crystal': 'assets/graphics/logos/crystal.svg',
  'cs': 'assets/graphics/logos/cs.svg',
  'css': 'assets/graphics/logos/css.svg',
  'dart': 'assets/graphics/logos/dart.svg',
  'delphi': 'assets/graphics/logos/delphi.svg',
  'dockerfile': 'assets/graphics/logos/dockerfile.svg',
  'elixir': 'assets/graphics/logos/elixir.svg',
  'erlang': 'assets/graphics/logos/erlang.svg',
  'flutter': 'assets/graphics/logos/flutter.svg',
  'fortran': 'assets/graphics/logos/fortran.svg',
  'glsl': 'assets/graphics/logos/glsl.svg',
  'go': 'assets/graphics/logos/go.svg',
  'gradle': 'assets/graphics/logos/gradle.svg',
  'haskell': 'assets/graphics/logos/haskell.svg',
  'java': 'assets/graphics/logos/java.svg',
  'javascript': 'assets/graphics/logos/javascript.svg',
  'json': 'assets/graphics/logos/json.svg',
  'julia': 'assets/graphics/logos/julia.svg',
  'kotlin': 'assets/graphics/logos/kotlin.svg',
  'langchain': 'assets/graphics/logos/langchain.svg',
  'less': 'assets/graphics/logos/less.svg',
  'llvm': 'assets/graphics/logos/llvm.svg',
  'lua': 'assets/graphics/logos/lua.svg',
  'makefile': 'assets/graphics/logos/makefile.svg',
  'nginx': 'assets/graphics/logos/nginx.svg',
  'nsis': 'assets/graphics/logos/nsis.svg',
  'ocaml': 'assets/graphics/logos/ocaml.svg',
  'ollama': 'assets/graphics/logos/ollama.svg',
  'perl': 'assets/graphics/logos/perl.svg',
  'php': 'assets/graphics/logos/php.svg',
  'powershell': 'assets/graphics/logos/powershell.svg',
  'python': 'assets/graphics/logos/python.svg',
  'ruby': 'assets/graphics/logos/ruby.svg',
  'rust': 'assets/graphics/logos/rust.svg',
  'scala': 'assets/graphics/logos/scala.svg',
  'scss': 'assets/graphics/logos/scss.svg',
  'supabase': 'assets/graphics/logos/supabase.svg',
  'swift': 'assets/graphics/logos/swift.svg',
  'toml': 'assets/graphics/logos/toml.svg',
  'typescript': 'assets/graphics/logos/typescript.svg',
  'vala': 'assets/graphics/logos/vala.svg',
  'xml': 'assets/graphics/logos/xml.svg',
  'html': 'assets/graphics/logos/html.svg',
  'yaml': 'assets/graphics/logos/yaml.svg',
};

// Map for programming language file extensions
Map<String, List<String>> programmingLanguagesFileExt = {
  'apache': ['htaccess', 'conf'],
  'arduino': ['ino'],
  'bash': ['sh', 'bash'],
  'c': ['c', 'h'],
  'clojure': ['clj', 'cljs', 'cljc'],
  'cmake': ['cmake', 'CMakeListstxt'],
  'cpp': ['cpp', 'hpp', 'h'],
  'crystal': ['cr'],
  'cs': ['cs'],
  'css': ['css'],
  'dart': ['dart'],
  'delphi': ['pas', 'dpr'],
  'dockerfile': ['Dockerfile'],
  'elixir': ['ex', 'exs'],
  'erlang': ['erl', 'hrl'],
  'flutter': ['dart'],
  'fortran': ['f90', 'f95', 'f03', 'f08'],
  'glsl': ['glsl', 'frag', 'vert'],
  'go': ['go'],
  'gradle': ['gradle'],
  'haskell': ['hs'],
  'java': ['java'],
  'javascript': ['js'],
  'json': ['json'],
  'julia': ['jl'],
  'kotlin': ['kt', 'kts'],
  'langchain': [],
  'less': ['less'],
  'llvm': ['ll', 'bc'],
  'lua': ['lua'],
  'makefile': ['Makefile'],
  'nginx': ['nginxconf'],
  'nsis': ['nsi', 'nsh'],
  'ocaml': ['ml', 'mli'],
  'ollama': [],
  'perl': ['pl', 'pm'],
  'php': ['php'],
  'powershell': ['ps1'],
  'python': ['py'],
  'ruby': ['rb'],
  'rust': ['rs'],
  'scala': ['scala', 'sc'],
  'scss': ['scss'],
  'supabase': [],
  'swift': ['swift'],
  'toml': ['toml'],
  'typescript': ['ts'],
  'vala': ['vala'],
  'xml': ['xml'],
  'html': ['html', 'htm'],
  'yaml': ['yaml', 'yml'],
};
