# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"7\n\nTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"\x1c\n\x0bTTSResponse\x12\r\n\x05track\x18\x01 \x01(\x0c\x32\x30\n\x03TTS\x12)\n\nSynthesize\x12\x0b.TTSRequest\x1a\x0c.TTSResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSREQUEST']._serialized_start=16
  _globals['_TTSREQUEST']._serialized_end=71
  _globals['_TTSRESPONSE']._serialized_start=73
  _globals['_TTSRESPONSE']._serialized_end=101
  _globals['_TTS']._serialized_start=103
  _globals['_TTS']._serialized_end=151
# @@protoc_insertion_point(module_scope)
